# Generated by Django 3.1.7 on 2021-04-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20210401_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='name',
            field=models.CharField(default='Null', max_length=25),
        ),
    ]
