# Generated by Django 3.1.7 on 2021-04-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_signupmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupModel',
        ),
    ]
