# Generated by Django 3.1.7 on 2021-04-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_generate_textmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generate_textmodel',
            old_name='Enter_Text',
            new_name='Text',
        ),
    ]
