# Generated by Django 3.1.7 on 2021-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20210401_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_textmodel',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
