# Generated by Django 3.1.7 on 2021-04-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_generate_textmodel_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Generate_Textmodel',
            new_name='GenerateTextmodel',
        ),
    ]
