# Generated by Django 3.1.7 on 2021-04-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20210401_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatetextmodel',
            old_name='name',
            new_name='Name',
        ),
    ]
