# Generated by Django 3.1.7 on 2021-04-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20210401_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatetextmodel',
            name='Name',
            field=models.CharField(max_length=20),
        ),
    ]
